import AuthProvider from "./components/authProvider/AuthProvider";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import AppContextProvider from "./components/context/HubContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IA Coworking Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
